name: Release & Publish Package

on:
  push:
    branches:
      - develop

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.version.outputs.changes }} # map step output to job output
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Enable node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # This step will run changeset version, setting the step output to if there were changesets found
      - name: Version command
        id: version
        run: |
          yarn
          echo ::set-output name=changes::$(npx changeset version 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')
      # Push the updated package.json, and CHANGESET.md files to github, this will trigger a new build
      # the || echo 'No changes' is to ignore errors from git when trying to commit and there are no changes
      - name: Push changes
        if: steps.version.outputs.changes == 'true'
        run: |
          git config user.email cicd@xdefi.io
          git config user.name "cicd"
          git add -A
          git commit -m "Version packages" || echo "No changes to commit"
          git push
  
  publish-gpr:
    runs-on: ubuntu-latest
    needs: version
    if: always() && needs.version.outputs.changes == 'false'
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@xdefi-tech'
      
      - name: Creating .yarnrc
        run: |
          cat <<'EOF' > .yarnrc
          npmScopes:
            'xdefi-tech':
            npmAlwaysAuth: true
            npmRegistryServer: 'https://npm.pkg.github.com/'
            npmAuthToken: $NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.PKG_TOKEN }}

      - name: Creating .npmrc
        run: |
          cat <<'EOF' > "$HOME/.npmrc"
          @xdefi-tech:registry=https://npm.pkg.github.com/
          //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.PKG_TOKEN }}

      - name: Install Dependencies
        run: yarn
      - name: Publish packages
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          NPM_TOKEN: ${{ secrets.PKG_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
