name: Release & Publish Package

on:
  push:
    branches:
      - develop

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@xdefi-tech'

      - name: Creating .npmrc
        run: |
            cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
            EOF
        env:
          NPM_TOKEN: ${{ secrets.PKG_TOKEN }}

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: yarn publish-packages
        env:
          NPM_TOKEN: ${{ secrets.PKG_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
