name: Release & Publish Package

on:
  push:
    branches:
      - develop

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@xdefi-tech'
      - name: Version command
        id: version
        run: |
          npm install --no-package-lock --no-save @changesets/cli
          echo ::set-output name=changes::$(npx changeset version 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')
      - name: Push changes
        if: steps.version.outputs.changes == 'true'
        run: |
          git config user.email cicd@xdefi.io
          git config user.name "cicd"
          git add .
          git commit -m "Version packages" || echo "No changes to commit"
          git push
  publish-gpr:
    runs-on: ubuntu-latest
    needs: version
    if: always() && needs.version.outputs.changes == 'false'
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@xdefi-tech'
      - run: yarn
      - run: npx changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PKG_TOKEN }}
