name: Release & Publish Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@xdefi-tech'
      - run: yarn
      - run: yarn workspace @xdefi-tech/chains-controller run publish:packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PKG_TOKEN }}
